export const formProps = {
  accountType: "",
  userID: "",
  password: "",
  confirmPassword: "",
  firstName: "",
  initial: "",
  lastName: "",
  maidenName: "",
  dob: "",
  ssn: "",
  ein: "",
  street: "",
  country: "",
  state: "",
  city: "",
  zipCode: "",
  email: "",
  phone1: "",
  phone2: "",
};
